version: "3"
services:
  db:
    platform: linux/x86_64
    image: postgres:13
    container_name: tabi-file.db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DATABASE: file
      POSTGRES_USER: file
      POSTGRES_PASSWORD: file123
      TZ: UTC
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
