service: ${self:custom.mainAppName.${opt:stage, 'dev'}}-functions

frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-hooks-plugin
  - serverless-prune-plugin

custom:
  mainAppName:
    dev: tabi-notification
  deploymentBuckets:
    dev: tabi-sls-bucket
  role:
    function: arn:aws:iam::434599936010:role/lambda-function-role
  prune:
    automatic: true
    includeLayers: true
    number: 3

  hooks:
    before:package:initialize:
      - env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o build/migration/bootstrap migration/main.go
      - zip -j build/migration/migration.zip build/migration/bootstrap .env
      
      # - env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o build/cron/notification/bootstrap cron/notification/main.go
      # - zip -j build/cron/notification/notification.zip build/cron/notification/bootstrap .env
    after:deploy:finalize:
      - rm -rf .serverless build

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  profile: tabi-backend
  timeout: 10
  memorySize: 128
  deploymentBucket:
    name: ${self:custom.deploymentBuckets.${opt:stage, 'dev'}}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  vpc:
    subnetIds:
      - subnet-0d79ec6d6b91e0850
      - subnet-07e6887c495a174af
    securityGroupIds:
      - sg-0c98f125a66e46b7b
  environment:
    STAGE: ${opt:stage, 'dev'}
    DEBUG: true
    DB_LOG: true
    CONFIG_NAME: ${self:custom.mainAppName.${opt:stage, 'dev'}}-${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::434599936010:role/lambda-function-role

package:
  individually: true
  patterns:
    - "!./**"
    - .env

functions:
  Migration:
    name: ${self:service}-migration-${opt:stage, 'dev'}
    timeout: 900
    handler: bootstrap
    package:
      artifact: build/migration/migration.zip
  # CronNotification:
  #   name: ${self:service}-cronnotification-${opt:stage, 'dev'}
  #   handler: bootstrap
  #   timeout: 900
  #   events:
  #     - schedule: cron(30 * * * ? *)
  #   package:
  #     artifact: build/cron/notification/notification.zip